version: "3.6"
services:

  portainer:
      image: portainer/portainer
      container_name: portainer
      restart: unless-stopped 
      command: -H unix:///var/run/docker.sock
      ports:
        - "9000:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/${user.user}/docker/portainer/data:/data
        - /home/${user.user}/docker/shared:/shared
      environment:
        - TZ=${timezone}
